# Generated by Django 3.2.19 on 2023-07-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_atul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='atul',
        ),
    ]
